/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Public configuration that the frontend may use to populate selects.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a new pipeline job and queue it for processing.
         */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Progress Stream
         * @description Server-Sent Events stream of pipeline progress.
         *
         *     Event types emitted:
         *       • `progress` — fired on every state change
         *       • `done`     — final event when the job completes successfully
         *       • `error`    — final event on pipeline failure
         *
         *     Each event's data is a JSON object matching ProgressEvent schema.
         */
        get: operations["progress_stream_api_jobs__job_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Init Upload
         * @description Initialise a direct upload. The client then PUTs the file bytes
         *     straight to the returned `upload_url`, then references `storage_key`
         *     when creating a job.
         */
        post: operations["init_upload_api_uploads_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Download Url
         * @description Get a fresh presigned download URL for a given storage key.
         */
        get: operations["get_download_url_api_uploads_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClipOut */
        ClipOut: {
            /** Id */
            id: string;
            /** Rank */
            rank: number;
            /** Title */
            title: string;
            /** Hook */
            hook: string;
            /** Emotion */
            emotion: string;
            /** Start Secs */
            start_secs: number;
            /** End Secs */
            end_secs: number;
            /** Duration Secs */
            duration_secs: number;
            /** Ensemble Score */
            ensemble_score: number;
            /** Llm Score */
            llm_score: number;
            /** Audio Score */
            audio_score: number;
            /** Spectral Score */
            spectral_score: number;
            /** Flow Score */
            flow_score: number;
            /** Chat Score */
            chat_score?: number;
            /** Status */
            status: string;
            /** Error Message */
            error_message?: string | null;
            /** Render Time Secs */
            render_time_secs: number;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Transcript Text */
            transcript_text?: string;
            /** Llm Reason */
            llm_reason?: string;
            /** Meme Keywords */
            meme_keywords?: string[];
            /**
             * Overlays
             * @default []
             */
            overlays: components["schemas"]["ClipOverlayOut"][];
            /** Download Url */
            download_url?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
        };
        /** ClipOverlayOut */
        ClipOverlayOut: {
            /** Id */
            id: string;
            /** Trigger Time Secs */
            trigger_time_secs: number;
            /** Duration Secs */
            duration_secs: number;
            /** Position */
            position: string;
            /** Similarity Score */
            similarity_score: number;
            /** Matched Keyword */
            matched_keyword: string;
        };
        /**
         * CreateJobRequest
         * @description Body for POST /api/jobs
         */
        CreateJobRequest: {
            /**
             * Source Url
             * @description A Twitch VOD, YouTube, Kick, or direct video URL.
             */
            source_url?: string | null;
            /**
             * Source Upload Key
             * @description Storage key from a prior upload (use /api/uploads/init first).
             */
            source_upload_key?: string | null;
            /**
             * Target Clips
             * @default 5
             */
            target_clips: number;
            /**
             * Caption Style
             * @default gaming_impact
             * @enum {string}
             */
            caption_style: "gaming_impact" | "tiktok_pop" | "minimal_white" | "podcast_clean";
            /**
             * Reframe Preset
             * @default fps_game
             * @enum {string}
             */
            reframe_preset: "fps_game" | "moba" | "battle_royale" | "irl" | "podcast" | "auto";
            /**
             * Content Profile
             * @default gaming
             * @enum {string}
             */
            content_profile: "gaming" | "irl" | "podcast" | "esports" | "general";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Redis */
            redis: boolean;
            /** Database */
            database: boolean;
            /** Storage */
            storage: boolean;
            /** Ollama */
            ollama?: boolean | null;
        };
        /** JobListItem */
        JobListItem: {
            /** Id */
            id: string;
            /** Source Title */
            source_title: string | null;
            /** Source Duration Secs */
            source_duration_secs: number | null;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Clip Count
             * @default 0
             */
            clip_count: number;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Source Url */
            source_url: string | null;
            /** Source Title */
            source_title: string | null;
            /** Source Duration Secs */
            source_duration_secs: number | null;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Current Stage */
            current_stage: string;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Content Profile */
            content_profile?: string | null;
            /**
             * Clips
             * @default []
             */
            clips: components["schemas"]["ClipOut"][];
        };
        /** UploadInitRequest */
        UploadInitRequest: {
            /** Filename */
            filename: string;
            /**
             * Content Type
             * @default video/mp4
             */
            content_type: string;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /** UploadInitResponse */
        UploadInitResponse: {
            /** Upload Id */
            upload_id: string;
            /** Upload Url */
            upload_url: string;
            /** Storage Key */
            storage_key: string;
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_stream_api_jobs__job_id__progress_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    init_upload_api_uploads_init_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadInitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadInitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_download_url_api_uploads_url_get: {
        parameters: {
            query: {
                /** @description Storage key */
                key: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
